name: Rust

on:
  push:
    branches: [main]
  pull_request:

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
  CLICOLOR: 1

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        rustv: [stable, beta]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: moonrepo/setup-rust@v1
        with:
          channel: ${{ matrix.rustv }}
          bins: cargo-nextest
          components: clippy,rustfmt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test
        run: cargo nextest run
      - name: Clippy
        run: cargo clippy -- -Dwarnings
      - name: fmt
        run: cargo fmt --check
